/*
 * blosc2_numexpr_integration.h
 * 
 * C header for calling NumExpr from C-Blosc2 worker threads
 * 
 * This header will be generated by Cython when compiling the .pyx file.
 * Include this in your C-Blosc2 code to call the NumExpr integration.
 */

#ifndef BLOSC2_NUMEXPR_INTEGRATION_H
#define BLOSC2_NUMEXPR_INTEGRATION_H

#include <Python.h>

#ifdef __cplusplus
extern "C" {
#endif

/*
 * Process a chunk using NumExpr from pure C code.
 * 
 * This function wraps C array pointers as NumPy arrays, evaluates a
 * pre-compiled NumExpr expression, and returns the result.
 * 
 * Parameters:
 * -----------
 * chunk_pointers : void**
 *     C array of pointers to decompressed chunk data.
 *     Example: void* chunks[3] = {chunk_a, chunk_b, chunk_c}
 * 
 * n_arrays : int
 *     Number of input arrays (length of chunk_pointers array)
 * 
 * chunk_size : int
 *     Number of elements in each chunk
 * 
 * dtype : int
 *     NumPy dtype number:
 *       NPY_DOUBLE = 12 (float64)
 *       NPY_FLOAT = 11 (float32)
 *       NPY_INT64 = 9
 *       NPY_INT32 = 7
 *     etc. (see numpy/ndarraytypes.h)
 * 
 * numexpr_handle : void*
 *     Handle to compiled NumExpr expression (obtained from setup_expression)
 * 
 * Returns:
 * --------
 * PyObject* : NumPy array with result (new reference)
 *             NULL on error (Python exception will be set)
 * 
 * Notes:
 * ------
 * - Caller does NOT need to hold the GIL (function acquires it internally)
 * - NumExpr will release the GIL internally during computation
 * - Caller must DECREF the returned PyObject when done
 * - This function does NOT take ownership of the input chunk_pointers
 * 
 * Example Usage:
 * --------------
 * // In C-Blosc2 worker thread (NO GIL initially)
 * 
 * // 1. Decompress chunks (NO GIL needed)
 * double* chunk_a = blosc2_decompress_chunk(ctx, chunk_idx, 0);
 * double* chunk_b = blosc2_decompress_chunk(ctx, chunk_idx, 1);
 * double* chunk_c = blosc2_decompress_chunk(ctx, chunk_idx, 2);
 * 
 * // 2. Create C array of pointers
 * void* chunks[3] = {chunk_a, chunk_b, chunk_c};
 * 
 * // 3. Call NumExpr (NO GIL needed - function handles it!)
 * PyObject* result = process_chunk_with_numexpr(
 *     chunks,           // C array of pointers
 *     3,                // number of inputs
 *     10000,            // chunk size
 *     NPY_DOUBLE,       // dtype (12)
 *     numexpr_handle    // expression handle
 * );
 * 
 * if (result == NULL) {
 *     // Handle error (need GIL to check Python exception)
 *     PyGILState_STATE gstate = PyGILState_Ensure();
 *     PyErr_Print();
 *     PyGILState_Release(gstate);
 * } else {
 *     // 4. Extract result data (need GIL for this)
 *     PyGILState_STATE gstate = PyGILState_Ensure();
 *     double* result_data = (double*)PyArray_DATA((PyArrayObject*)result);
 *     
 *     // Copy data while we have GIL
 *     memcpy(my_buffer, result_data, chunk_size * sizeof(double));
 *     
 *     // 5. Cleanup
 *     Py_DECREF(result);
 *     PyGILState_Release(gstate);
 *     
 *     // 6. Use copied data (NO GIL needed)
 *     blosc2_compress_chunk(output, my_buffer, chunk_size);
 * }
 * 
 * free(chunk_a);
 * free(chunk_b);
 * free(chunk_c);
 */
PyObject* process_chunk_with_numexpr(
    void** chunk_pointers,
    int n_arrays,
    int chunk_size,
    int dtype,
    void* numexpr_handle
);

#ifdef __cplusplus
}
#endif

#endif /* BLOSC2_NUMEXPR_INTEGRATION_H */
