name: Validate static types
permissions: read-all

on:
  pull_request:
    paths:
      - .github/workflows/typecheck.yml
      - numexpr/*
      - pyproject.toml
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  typecheck_quaddtype:
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - uses: actions/checkout@v5.0.0

      - uses: astral-sh/setup-uv@v6.7.0
        with:
          activate-environment: true
          python-version: "3.10"

      - name: install
        run: uv pip install mypy pyright pytest .

      - name: pyright
        run: pyright

      - name: mypy
        run: mypy --no-incremental --cache-dir=/dev/null .
